### ISSUE TITLE
Propositions for enhancement

### ISSUE THREAD

**Issue by egregors** [logux/backend-test#8]
I believe `logix-backend-test` could make the development process much easier but some points look confusing for now.

This is a few problems I got during adding proto4 support according to Spec + backend-test:

- [ ] Every test should be represented in the Readme like a separate step
- [ ] Step / Test number should match the number of step description in Readme 
- [ ] Steps description in Readme should be in the same order as in the tests 
- [ ] Every step should contain a link to the documentation if it necessary
- [ ] We need to decide how to be with the backend persistent state during the tests. Looks like `backend-test` expect DB wipe every step. It seems unusual if we are running them like integration tests. I mean, it's OK, if we run each test separated. But otherwise, when all tests run at once, each next test does not expect state changes made by the previous tests.

**Comment by ai** [comment]
> Every test should be represented in the Readme like a separate step

I am not sure that it is a best idea. We could have a separate positive and negative test for the same feature.

But we can:

1. Remove `<ol>` from the docs to stop confusing between step number and test number.
2. Add a description for each test.

> Looks like backend-test expect DB wipe every step

Nope. The local Node.js doesn’t wipe data between steps. But it wipes steps between runs (because it stores the data in the memory).

Do we need to add recommendation to use in-memory DB in the test app?

**Comment by egregors** [comment]
@ai 
> Remove <ol> from the docs to stop confusing between step number and test number.
> Add a description for each test.
LGTM

> Nope. The local Node.js doesn’t wipe data between steps. But it wipes steps between runs (because it stores the data in the memory).
Do we need to add recommendation to use in-memory DB in the test app?

IDK... For TDD-like developing it will a bit awkward, because you must restart the server each test run. 

For example: Right now I run the tests on empty DB, get 18 passed, add some fix, rerun tests, and get only 10 passed because the 11th test failed if DB already contains user with id == 10

I suggest a more universal and less confusing way. I think, will be cool if each complex test case will include setUp and tearDown parts. 
For example, if the test case began on an empty Users list in DB, but need to create few users for check somethings, the test case should remove them after the test passed (tearDown). Still by some regular `UserRemove` action, without any tricks.

For me, it looks convenient for both TDD and all cases runs. And it could help us integrate backend-test into CI.

**Comment by ai** [comment]
> I suggest a more universal and less confusing way. I think, will be cool if each complex test case will include setUp and tearDown parts.

You need to do it on your side because it depends on the back-end language.

You can have `make integration_test` script, which will clean DB, start back-end, and run `npx @logux/backend-test`.

Because every back-end will have own system to run tests, I am not sure that we need to put it to this script.

**Comment by egregors** [comment]
> I have no idea how to set setUp and tearDown for each test because his project does not know how back-end is saving the data.

I mean each backend could implement CRUD actions for Users, and you will get full control of users store state by actions to create | delete records from Logux app.

But if it's a problem, I already have done with it on my side: https://github.com/logux/django/commit/d1f69dae0ad495f285f90927543c0d3ec31e1551

**Comment by ai** [comment]
> I mean each backend could implement CRUD actions for Users, and you will get full control of users store state by actions to create | delete records from Logux app.

For now, I want to keep the test app API as simple as possible.

I am working on PostCSS 8 now and will not be able to find time for big changes in testing API.

> But if it's a problem, I already have done with it on my side

Perfect, let’s keep it a little dirty for now. Maybe later when we have more backend integrations we will change it.
